apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openebs-test-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-hostpath  # Modifica questo con il tuo StorageClass se necessario
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: openebs-test-pod
spec:
  containers:
  - name: test-container
    image: nginx
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(date) >> /mnt/openebs/test.txt; sleep 5; done"]
    volumeMounts:
    - mountPath: /mnt/openebs
      name: openebs-volume
  volumes:
  - name: openebs-volume
    persistentVolumeClaim:
      claimName: openebs-test-pvc